# Generated by Django 2.1.13 on 2019-10-19 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('bio', models.TextField(help_text='Write something about you')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='code_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('slug', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'draft')], max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devdevout.BlogAuthor')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devdevout.Category')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-created_at', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('videofile', models.FileField(blank=True, upload_to='')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('links', models.URLField(blank=True)),
                ('madewith', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('compatible', models.CharField(blank=True, max_length=100)),
                ('responsive', models.CharField(blank=True, max_length=100)),
                ('dependencies', models.CharField(blank=True, max_length=100)),
                ('code_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devdevout.code_post')),
            ],
        ),
    ]
