# Generated by Django 2.2.6 on 2019-11-29 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devdevout', '0003_auto_20191121_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devdevout.Category'),
        ),
    ]
