# Generated by Django 2.2.6 on 2019-11-29 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devdevout', '0004_sub_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sub_catagory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='devdevout.Sub_Category'),
            preserve_default=False,
        ),
    ]
